import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync } from "fs";
import { dirname } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Function to copy built files to target directories
function copyToTargets() {
	const files = ["main.js", "manifest.json", "styles.css"];
	const targets = [
		"./dist"
	];

	// Add vault path if specified via environment variable (for local development)
	if (process.env.OBSIDIAN_VAULT_PLUGIN_DIR) {
		targets.push(process.env.OBSIDIAN_VAULT_PLUGIN_DIR);
	}

	targets.forEach(targetDir => {
		try {
			// Create directory if it doesn't exist
			mkdirSync(targetDir, { recursive: true });

			// Copy each file
			files.forEach(file => {
				copyFileSync(file, `${targetDir}/${file}`);
				console.log(`✓ Copied ${file} to ${targetDir}`);
			});
		} catch (error) {
			console.error(`✗ Failed to copy to ${targetDir}:`, error.message);
		}
	});
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	copyToTargets();
	process.exit(0);
} else {
	await context.watch();
}
